class Autogenerated {
  List<Giris>? giris;

  Autogenerated({this.giris});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['giris'] != null) {
      giris = <Giris>[];
      json['giris'].forEach((v) {
        giris!.add(new Giris.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.giris != null) {
      data['giris'] = this.giris!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Giris {
  String? kadi;
  String? sifre;
  String? plasiyerId;
  String? adi;
  String? soyadi;
  String? username;
  String? uid;
  String? calismasekli;
  String? entegrator;
  String? entegratorkullanici;
  String? entegratorsifre;
  String? entegratorkontur;
  String? vergino;
  String? vergidairesi;
  String? plasiyerAdi;
  String? kullaniciId;
  String? firmaLogo;

  Giris(
      {this.kadi,
        this.sifre,
        this.plasiyerId,
        this.adi,
        this.soyadi,
        this.username,
        this.uid,
        this.calismasekli,
        this.entegrator,
        this.entegratorkullanici,
        this.entegratorsifre,
        this.entegratorkontur,
        this.vergino,
        this.vergidairesi,
        this.plasiyerAdi,
        this.kullaniciId,
        this.firmaLogo});

  Giris.fromJson(Map<String, dynamic> json) {
    kadi = json['kadi'];
    sifre = json['sifre'];
    plasiyerId = json['PlasiyerId'];
    adi = json['adi'];
    soyadi = json['soyadi'];
    username = json['username'];
    uid = json['uid'];
    calismasekli = json['calismasekli'];
    entegrator = json['entegrator'];
    entegratorkullanici = json['entegratorkullanici'];
    entegratorsifre = json['entegratorsifre'];
    entegratorkontur = json['entegratorkontur'];
    vergino = json['vergino'];
    vergidairesi = json['vergidairesi'];
    plasiyerAdi = json['PlasiyerAdi'];
    kullaniciId = json['KullaniciId'];
    firmaLogo = json['FirmaLogo'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['kadi'] = this.kadi;
    data['sifre'] = this.sifre;
    data['PlasiyerId'] = this.plasiyerId;
    data['adi'] = this.adi;
    data['soyadi'] = this.soyadi;
    data['username'] = this.username;
    data['uid'] = this.uid;
    data['calismasekli'] = this.calismasekli;
    data['entegrator'] = this.entegrator;
    data['entegratorkullanici'] = this.entegratorkullanici;
    data['entegratorsifre'] = this.entegratorsifre;
    data['entegratorkontur'] = this.entegratorkontur;
    data['vergino'] = this.vergino;
    data['vergidairesi'] = this.vergidairesi;
    data['PlasiyerAdi'] = this.plasiyerAdi;
    data['KullaniciId'] = this.kullaniciId;
    data['FirmaLogo'] = this.firmaLogo;
    return data;
  }
}